padsweb/urls.py
#
#
# Public Archive of Days Since Timers
# Routes
#
#

from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'padsweb'
urlpatterns = [
    #
    # Timer Read URLs
    # 
    # Public Index
    url(r'^$', views.index, name='index'),
    url(r'^timers/$', views.index, name='index_alt'),
    # Personal Index
    url(r'^timers/personal/$', views.index_personal, name='index_personal'),
    # Private Timers by User (private)
    url(r'^timers/personal/private/$', views.index_private_by_user, 
        name='index_private_by_user'),
    # Personal Timer Groups Index for signed-in User (private)
    url(r'^timers/personal/groups/$', views.index_personal_groups, 
        name='index_personal_groups'),
    # Timers by Group
    url(r'^timers/group/(?P<timer_group_id>[0-9]+)/$', 
        views.index_group, name='index_group'),
    # Shared Timers by User 
    url(r'^timers/shared/user/(?P<user_id>[0-9]+)/$', 
        views.index_shared_by_user, name='index_shared_by_user'),
    # Longest Running Timers
    url(r'^timers/shared/longest_running/$', 
        views.index_longest_running, name='index_longest_running'),    
    # Recently Reset Timers
    url(r'^timers/shared/recent_resets/$', views.index_recent_resets,
        name='index_recent_resets'),    
    # Newest Timers
    url(r'^timers/shared/newest/$', views.index_newest, name='index_newest'),    
    
    #
    # Timer URLs
    #
    # Timer Detail View:
    url(r'^timer/(?P<timer_id>[0-9]+)/$', views.timer, name='timer'),
    # Timer Detail Vies, via Permalink
    path('timer/link/<slug:link_code>/',
        views.timer_by_permalink, name='timer_by_permalink'),
    # Timer Export to JSON
    url(r'^timer/export/(?P<timer_id>[0-9]+)/$', views.timer_export, 
        name='timer_export'),

    #
    # Timer Configuration URLs
    #
    # Timer Creation
    url(r'^timer/new/$', views.timer_new, name='timer_new'),
    # Set Timer Groups
    url(r'^timer/(?P<timer_id>[0-9]+)/set_groups/$', 
        views.timer_set_groups, name='timer_set_groups'),
    # Timer Delete    
    url(r'^timer/(?P<timer_id>[0-9]+)/delete/$', views.timer_del, 
        name='timer_del'),
    # Timer Reset
    url(r'^timer/(?P<timer_id>[0-9]+)/reset/$', views.timer_reset, 
        name='timer_reset'),
    # Timer Share
    url(r'^timer/(?P<timer_id>[0-9]+)/share/$', views.timer_share, 
        name='timer_share'),
    # Timer Unshare    
    url(r'^timer/(?P<timer_id>[0-9]+)/unshare/$', views.timer_unshare, 
        name='timer_unshare'),
    # Timer Rename    
    url(r'^timer/(?P<timer_id>[0-9]+)/rename/$', views.timer_rename, 
        name='timer_rename'),    
    # Timer Suspend / Stop
    url(r'^timer/(?P<timer_id>[0-9]+)/stop/$', views.timer_stop, 
        name='timer_stop'),
    # Add Timer to Group
    url(r'^timer/(?P<timer_id>[0-9]+)/add_to_group/$', 
        views.timer_add_to_group, name='timer_add_to_group'),    
    # Remove Timer from Group    
    url(r'^timer/(?P<timer_id>[0-9]+)/remove_from_group/$', 
        views.timer_remove_from_group, name='timer_remove_from_group'),    
    
    #
    # User Account URLs
    #
    # User Sign In
    url(r'^sign_in/$', views.session_new, name='session'),
    # Quick List User Sign In
    url(r'^sign_in/quicklist/$', views.session_quicklist, 
        name='session_quicklist'),        
    # User Sign Out
    url(r'^sign_out/$', views.session_end, name='session_end'),
    # User Sign Up Intro
    url(r'^sign_up/$', views.sign_up_sign_in_intro, name='sign_up_intro'),
    # User Sign Up
    url(r'^sign_up/user/$', views.user_new, name='sign_up_user'),
    # Quick List User Sign Up
    url(r'^sign_up/quicklist/$', views.quicklist_new, 
        name='sign_up_quicklist'),

    #
    # User Account Configuration URLs
    #
    # User Settings
    url(r'^setup/$', views.settings_info, name='settings_info'),
    # User Settings: new Timer Group
    url(r'^timers/group/new/$', views.settings_new_timer_group, 
        name='settings_new_timer_group'),
    # User Settings: delete Timer Group
    url(r'^timers/group/delete$', views.settings_delete_timer_group, 
        name='settings_delete_timer_group'),
    # User Settings Password Change
    url(r'^setup/password$', views.settings_set_password, 
        name='settings_set_password'),    
    # User Settings Time Zone Change
    url(r'^setup/time_zone', views.settings_set_tz, name='settings_set_tz'),
    # User Settings Import Quick List
    url(r'^setup/import_ql/$', views.settings_import_ql, 
        name='settings_import_ql'),
     # User Info Export to JSON
    url(r'^setup/export_all', views.user_export_all, name='user_export_all')
        
    ]

padsweb/templates/padsweb/padsweb.html
<!DOCTYPE html>
{# PADS Base Template #}
{% load static %}
{% load tz %}

<html>
	<head>
		<meta charset="UTF-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=0">
		<title>{% block title %}PADS{% endblock %}</title>
		<link rel="stylesheet" href="{% static 'padsweb/css/pads-orlok-f2-2.css' %}"/>
	</head>
	<body class="zero-margin zero-padding">
		{# Header and Navigation #}
		<header>
			<nav class="header-nav">
				<ul class="nav-menu">
					{# Options when NOT signed in #} 
						<li id="pads-title">P.A.D.S.</li>
					{% if not signed_in %}
						<li><a href="{% url 'padsweb:index' %}">Index</a></li>
						<li><a href="{% url 'padsweb:sign_up_intro' %}">Sign Up/In To Create Timers</a></li>
					{# Options when SIGNED in #}
					{% else %}
						{% if user.is_anonymous %}
							<li><a href="{% url 'padsweb:timer_new' %}">New</a></li>
							<li><a href="{% url 'padsweb:index_personal' %}">Timers</a></li>
							<li><a href="{% url 'padsweb:index' %}">Public</a></li>
						{% else %}
							<li><a href="{% url 'padsweb:timer_new' %}">New</a></li>
							<li><a href="{% url 'padsweb:index_personal' %}">Timers</a></li>
							<li><a href="{% url 'padsweb:index_personal_groups' %}">Groups</a></li>
							<li><a href="{% url 'padsweb:index' %}">Public</a></li>
						{% endif %}
					{% endif %}
					{# Sign Out and Options Link #}
					{% if signed_in %}
						<li id="user-name-display">
							{{ user.username }}(
							<a href="{% url 'padsweb:settings_info' %}">Setup</a> /
							<a href="{% url 'padsweb:session_end' %}">SignOut</a>
							)
						</li>
					{% endif %}
					<div id="hot-air"></div>
				</ul>
				<div id="ql-password-input">
					<div id="hot-air"></div>
				</div>		 		
				<div id="hot-air"></div>
			</nav>
		</header>
		{# Content #}
		<main>
			{% if banner_text %}
			<aside class="banner {{ banner_type }}">
					<p class="zero-margin zero-padding">{{ banner_text }}</p>
			</aside>
			{% endif %}
			{% timezone time_zone %}
			{% block content %}{% endblock %}
			{% endtimezone %}
		</main>
		{# Footer #}
		<footer id="global-footer">
			<p>Public Archive of &lsquo;Days Since&rsquo; Timers</p>
			<p>
				Jump To: <a href="{% url 'padsweb:index' %}">Public Archive</a>
				{% if signed_in %}
				 / <a href="{% url 'padsweb:index_personal' %}">Your Timers</a>
				{% endif %}
				/ <a href="{% url 'padsweb:index_personal_groups' %}">Your Groups</a>
			</p>
			<p>Test Version {{app_version}} &copy; 2017 Mounaiban</p>
			<p>Your Olson time zone is {{time_zone}}</p>
		</footer>		
	</body>
</html>

padsweb/templates/padsweb/sign_up.html
{% extends "padsweb/padsweb.html" %}
{# User Registration View #}

{% block title %}Account Registrations at the Personal Archive of &lsquo;Days Since&rsquo; Timers{% endblock %}

{% block content %}
	<article class="forms-and-options sp-100 ll-75-left forms-normal">
	{# Sign In Form #}
		<section>
			<h1>Sign In</h1>
			<form action="{% url 'padsweb:session' %}" method="post">
				<p>Already have an account? Sign in here!</p>
				{% csrf_token %}
				<div class="forms-input-label-set">
					{{sign_in_form.username.label_tag}}
					{{sign_in_form.username}}
				</div>
				<div class="forms-input-label-set">
					{{sign_in_form.password.label_tag}}
					{{sign_in_form.password}}
				</div>
				<input type="submit" value='Sign in'/>
			</form>
		</section>
	</article>
	<article class="forms-and-options sp-100 ll-25-right forms-normal">
	{# Quick List Sign-in Form #}
		<section>
			<h1>Open Quick List</h1>
				<p>If you have created a quick list, enter the password here to open it.</p>
				<form action="{% url 'padsweb:session_quicklist' %}" method="post">
					{% csrf_token %}
					<div class="forms-input-label-set">
						{{sign_in_quicklist_form.password.label_tag}}
						{{sign_in_quicklist_form.password}}
					</div>
					<input type="submit" value='Open QL'/>
				</form>
		</section>
	</article>
	<article class="forms-and-options sp-100 ll-25-right forms-normal">
	{# Quick List Creation Form #}
		<section>
			<h1>New Quick List</h1>
			<form action="{% url 'padsweb:sign_up_quicklist' %}" method="post">
				<p>A Quick List allows you to start creating your own count-up timers on PADS instantly.</p>
				<p>A random password will be generated for you to open and edit the list.</p>
				{% csrf_token %}
				<input type="submit" value='Create Quick List'/>
			</form>
		</section>
	</article>
	<article class="forms-and-options sp-100 ll-75-left forms-normal">
	{# Sign-up Form #}
		<section>
			<h1>Sign Up For A New Account</h1>
			<form action="{% url 'padsweb:sign_up_user' %}" method="post">
				<p>Sign up for a regular account accessible with a username and password.</p>
				{% csrf_token %}
				<div>
					<div class="forms-input-label-set">
						{{sign_up_form.username.label_tag}}
						{{sign_up_form.username}}
					</div>
					<div class="forms-input-label-set">
						{{sign_up_form.password.label_tag}}
						{{sign_up_form.password}}
					</div>
					<div class="forms-input-label-set">
						{{sign_up_form.password_confirm.label_tag}}
						{{sign_up_form.password_confirm}}
					</div>
					<div class="forms-input-label-set">
						<input type="submit" value='Sign Up!'/>
					</div>
				</div>
			</form>
		</section>
		<div id="hot-air"></div>
	</article>
{% endblock %}

padsweb/templates/padsweb/timer.html
{% extends "padsweb/padsweb.html" %}
{# Timer Detail Template #}

{% block title %}
	{{timer.get_heading}} - PADS
{% endblock%}

{% block content %}
	<article class="sp-100 zero-margin item-detail">
		<section>
			<h1>{{ timer.get_running_time_string }}</h1>
				{% if timer.is_running %}
					<p>({{ timer.count_from_date_time | timesince }})</p>
					<h2>Since</h2>
						<p id="item-detail-blurb">{{ timer.get_description }}</p>
					<h2>Counting from</h2>
						<p>{{ timer.count_from_date_time }}</p>
				{% else %}
					<h2>Last Running Time When</h2>
						<p id="item-detail-blurb">{{ timer.get_description }}</p>
					<h2>This Timer was suspended on</h2>
						<p>{{ timer.reset_history_latest.date_time }}</p>
				{% endif %}
				<h2>Created on</h2>
					<p>{{ timer.creation_date_time }}
					{% if timer.is_pre_dated %}
						<p>(this timer's current count is back-dated)</p>
					{% endif %}
			
				<h2>Owner</h2>
					<p>{{ timer.creator_user_nickname_short }}</p>
				
				<h2>Permalink</h2>
					<p>{{ permalink_prefix }}{{ timer.get_permalink_url }}</p>
		</section>		
	</article>
	
	{# Timer History #}
	<article class="index-article-group index-group-feature-dark ll-100 sp-100">
		<header>
			<h2>Timer History</h2>
		</header>
		<section>
		{% if timer.reset_count > 0 %}
			{% for h in timer.reset_history %}
			<article class="index-article-item index-item-normal">
				<header>
					<h3>
					{{h.date_time|timesince}} ago
					</h3>
				</header>
				<section>
					<p>{{ h.reason }}</p>
				</section>
				<footer>
					<p>{{h.date_time}}</p>
				</footer>
			</ul>
			</article>
			{% endfor %}
		{% else %}
			<h3>No timer history found...</h3>
		{% endif %}
		</section>
		<footer>
		</footer>
		<div id="hot-air"></div>
	</article>
	
	{# Options for Editing Timers #}
	{% if edit_enabled %}
		{# Timer Reset #}
		{% if not timer.is_historical %}
			<article class="forms-and-options forms-help ll-25-right sp-100">
				<section>
					<h1>Timer Reset</h1>
						<p>Resetting a timer makes it begin counting from zero days again.</p>
				</section>
			</article>
			<article class="forms-and-options forms-normal ll-75-left sp-100">
				<section>
				<h2>Reset This Timer</h2>
					{% if not timer.is_running %}
					<p>This timer has been suspended. Reset it to get it running again.</p>
					{% endif %}
					<p>This operation cannot be undone. Resets are recorded in the Timer History.</p>
					<form action="{% url 'padsweb:timer_reset' timer.id %}" method="post">
						{% csrf_token %}
						{{ reason_form.reason.label_tag }}
						{{ reason_form.reason }}
						<input type='submit' value='Reset Timer'/>
					</form>
				</section>
			</article>
		{% endif %}
	
		{# Timer Stops and Suspensions #}
		{% if timer.is_historical %}
			{# Options For Historical Timers #}
			{% if timer.is_running %}
			<article class="forms-and-options forms-normal ll-75-left sp-100">
				<section>
				<h2>Stop Historical Timer</h2>
					<p>This action is not undoable.</p>
					<form action="{% url 'padsweb:timer_stop' timer.id %}" method="post">
						{% csrf_token %}
						{{ reason_form.reason.label_tag }}
						{{ reason_form.reason }}
						<input type='submit' value='Stop Timer'/>
					</form>
				</section>
			</article>			
			{% else %}
			<article class="forms-and-options forms-normal ll-75-left sp-100">
				<h2>Historical Timer Stopped</h2>
				<section>
					<p>This Timer has been Stopped and shall not be restarted.</p>
				</section>
			</article>
			{% endif %}
		{% else %}
			{# Options for Regular Timers #}
			{% if timer.is_running %}
				<article class="forms-and-options forms-normal ll-75-left sp-100">
					<h2>Suspend Timer</h2>
					<section>
						<p>This cannot (really) be undone.</p>
						<form action="{% url 'padsweb:timer_stop' timer.id %}" method="post">
							{% csrf_token %}
							{{ reason_form.reason.label_tag }}
							{{ reason_form.reason }}
							<input type='submit' value='Suspend Timer'/>
						</form>
					</section>
				</article>			
			{% endif %}
		{% endif %}
			
		{# Timer Sharing #}
		<article class="forms-and-options sp-100 ll-25-right forms-help">
			<section>
			<h1>Timer Sharing</h1>
				<p>Sharing a timer makes it visible on the Public Archive.</p>
			</section>
		</article>
		<article class="forms-and-options sp-100 ll-75-left forms-normal">
			<section>
			{% if timer.is_public %}
				<h2>Make Timer Private</h2>
					<form action="{% url 'padsweb:timer_unshare' timer.id %}" method="post">
						{% csrf_token %}
						<input type='submit' value='Hide Timer'/>
					</form>				
			{% else %}
				<h2>Make Timer Public</h2>
					<form action="{% url 'padsweb:timer_share' timer.id %}" method="post">
						<p>The timer is currently private. Avoid sharing sensitive information.</p>
						{% csrf_token %}
						<input type='submit' value='Share Timer'/>
					</form>
			{% endif %}
			</section>
		</article>
		
		{# Timer Groups #}
		{% if not user.is_anonymous %}
			<article class="forms-and-options forms-help sp-100 ll-25-right">
				<section>
					<h1>Groups</h1>
						<p>Organise your timers by adding them to a Timer Group.</p>
				</section>
			</article>
			<article class="forms-and-options sp-100 ll-75-left forms-normal">
				<section>
					<h2>Groups</h2>
					<h2>Enter Timer Groups</h2>
						<form action="{% url 'padsweb:timer_set_groups' timer.id %}" method="POST">
    						<p>
        						Please enter names of all Timer Groups you want to include
                				this timer in, separated by spaces. Timer Groups will be 
                				automatically created for you.
        					</p>
							{% csrf_token %}
							{{ set_timer_inclusions_form.group_names.label_tag }}
							{{ set_timer_inclusions_form.group_names }}
							<input type="submit" value="Set Timer Groups" />
							<p>
        							To see a list of groups created for you, or to delete
        							them, <a href="{% url 'padsweb:settings_info' %}">go to your Options page.</a>
							</p>
						</form>        					
				</section>
			</article>
		{% endif %}
		
		{# Timer Renaming #}
		{% if not timer.is_historical %}
			<article class="forms-and-options sp-100 ll-25-right forms-help">
				<section>
					<h1>Edit Timer Description</h1>
					<p>You can change a timer's description. Changing a timer's description automatically resets it.</p>
				</section>
			</article>
			<article class="forms-and-options sp-100 ll-75-left forms-normal">
				<section>
					<h2>Edit Timer Description</h2>
						<p>This cannot (really) be undone.</p>
						<form action="{% url 'padsweb:timer_rename' timer.id %}" method="post">
							{% csrf_token %}
							{{ rename_timer_form.description.label_tag }}
							{{ rename_timer_form.description }}
							<input type='submit' value='Reset &amp; Change Description'>
						</form>
				</section>
			</article>
		{% endif %}
		<article class="forms-and-options sp-100 ll-25-right forms-help">
			<section>
				<h1>Delete Timer</h1>
				<p>Pretty much self-explanatory.</p>
			</section>
		</article>
		<article class="forms-and-options sp-100 ll-75-left forms-normal">
			<section>
				<h2>Delete Timer</h2>
					<form action="{% url 'padsweb:timer_del' timer.id %}" method="post">
						<p>This operation cannot be undone.</p>		
						{% csrf_token %}
						<input type='submit' value='Delete Timer'/>
					</form>
			</section>
		</article>
	{% endif %}
{% endblock %}

padsweb/templates/padsweb/timer_new.html
{% extends "padsweb/padsweb.html" %}
{# New Timer Page, With Extra Options #}
{% block title %}Set Up New Timer{% endblock %}
{% block content %}
	{% if signed_in %}
		<article class="forms-and-options sp-100 ll-100 forms-normal">
			<section>
				<h1>Create a Timer</h1>
				<form action = "{% url 'padsweb:timer_new' %}" method="post">
					{% csrf_token %}
					<section>
						<h2>Timer Description</h2>
						<p>Enter a description for your timer.</p>
							<div class="forms-input-label-set">
								{{ add_new_timer_form.description.label_tag }}
								{{ add_new_timer_form.description }}
								<span>{{ add_new_timer_form.description.help_text }}</span>
							</div>
					</section>
						<h2>Creation Message</h2>
						<p>Enter a creation message for your new Timer.</p>
						<p>This message will appear as the first entry of
							your Timer's History.</p>
							<div class="forms-input-label-set">
								{{ add_new_timer_form.first_history_message.label_tag }}
								{{ add_new_timer_form.first_history_message }}
							</div>
					<section>
					</section>
					<section>					
						<h2>Timer Initial Date &amp; Time Type</h2>
							<p>By default, the current date and time will be used.
								The new Timer will start counting from zero days.</p>

							<p>Alternatively, specify a past date and time to use as the
								initial date and time, if you don&apos;t want your Timer to
								count from zero.</p>
							<p>Please be aware that the date time below will be 
								<strong>ignored</strong> if the Use Current Date
								And Time option is enabled.</p>
							<div class="forms-input-label-set">
								{{ add_new_timer_form.year.label_tag }}
								{{ add_new_timer_form.year }}
							</div>
							<div class="forms-input-label-set">
								{{ add_new_timer_form.month.label_tag }}
								{{ add_new_timer_form.month }}
							</div>
							<div class="forms-input-label-set">
								{{ add_new_timer_form.day.label_tag }}
								{{ add_new_timer_form.day }}
							</div>
							<div class="forms-input-label-set">
								{{ add_new_timer_form.hour.label_tag }}
								{{ add_new_timer_form.hour }}
							</div>
							<div class="forms-input-label-set">
								{{ add_new_timer_form.minute.label_tag }}
								{{ add_new_timer_form.minute }}
							</div>							
							<div class="forms-input-label-set">
								{{ add_new_timer_form.second.label_tag }}
								{{ add_new_timer_form.second }}
							</div>							
							<div class="forms-input-label-set">
								{{ add_new_timer_form.use_current_date_time.label_tag }}
								{{ add_new_timer_form.use_current_date_time }}
							</div>
					</section>
					<section>
							<input type="submit" value="Create Timer!"/>
					</section>
					<h1>More Options</h1>
					<section>
						<h2>Historical Timer</h2>
							<p>Check the box below to create a Historical Timer.
							These timers cannot be reset.</p>
							<p>Historical timers can be stopped once, and
							once stopped, cannot be restarted.</p>
							<div class="forms-input-label-set">
								{{ add_new_timer_form.historical.label_tag }}
								{{ add_new_timer_form.historical }}
							</div>
					</section>
					<section>
						<input type="submit" value="Create Timer!"/>
					</section>
				</form>
			</section>
		</article>
	{% endif %}
{% endblock %}

padsweb/templates/padsweb/user_settings.html
{% extends "padsweb/padsweb.html" %}
{# User Accounts Settings Template #}

{% block title %}Personal Archive of &lsquo;Days Since&rsquo; Timers{% endblock %}

{% block content %}
		{% if signed_in %}
			{# Quick List Options #}
			<article class="sp-100 ll-100 item-detail">
				<section>
				{% if user.is_anonymous %}
					<h1>Quick List Opened</h1>
				{% else %}
					<h1>{{user_nickname_short}}</h1>
					<h2>Member Since</h2>
					<p>{{user.user_from_db.sign_up_date_time}}</p>
				{% endif %}
				</section>
			</article>
			<article class="forms-and-options forms-help sp-100 ll-25-right">
				<section>
					<h1>Time Zone</h1>
						<p>Choose from a selection of over 500 time zones,
						including historical and test zones!</p>
						<p>Time zones are shown in Olson format. Please use
						the Continent/City or Ocean/City time zones when 
						you are not hacking.</p>
				</section>
			</article>
			<article class="forms-and-options forms-normal sp-100 ll-75-left">
				<section class="forms-and-options">
					<h2>Select Time Zone</h2>
						<form action="{% url 'padsweb:settings_set_tz' %}" method="POST">
							{% csrf_token %}
							{{time_zone_form.time_zone.label_tag}}
							{{time_zone_form.time_zone}}
						<input type="submit" value="Change Timezone"/>
						</form>
				</section>
			</article>			
			{# Regular User Options #}
			{% if not user.is_anonymous %}
			<article class="forms-and-options forms-help sp-100 ll-25-right">
				<section>
					<h1>Timer Groups</h1>
						<p>
        						Timer Groups are used to organise your Timers.
        						They are automatically created for you when you assign group
        						names to a Timer.
						</p>
						<p>
        						To delete a Timer Group, select a group from the list, and
        						then press the Delete button. Deleting a group only unassigns
        						Timers from the deleted Group.
        					</p>
				</section>
			</article>
			<article class="forms-and-options forms-normal sp-100 ll-75-left">
				<section>
					<h2>Delete A Timer Group</h2>
						<form action="{% url 'padsweb:settings_delete_timer_group' %}" method="POST">
							{% csrf_token %}
							{{delete_timer_group_form.label_tag}}
							{{delete_timer_group_form}}
							<input type="submit" value="Delete Timer Group"/>
						</form>
						<div id="hot-air"></div>
					</form>
				</section>
			</article>
			<article class="forms-and-options forms-help sp-100 ll-25-right">
				<section>
					<h1>Quick Lists</h1>
					<p>You can transfer timers in a Quick List to your account.</p>
					<p>Timers can be imported into a Timer Group.</p>
					<p>Please be aware that the Quick List will be deleted, and its password rendered permanently
						unusable.</p>
				</section>
			</article>
			<article class="forms-and-options forms-normal sp-100 ll-75-left">
				<section>
					<h2>Import Quick List</h2>
					<form action="{% url 'padsweb:settings_import_ql' %}" method="POST">
						{% csrf_token %}
						<div class="forms-input-label-set">
							{{quick_list_import_form.password.label_tag}}
							{{quick_list_import_form.password}}
						</div>
						<div class="forms-input-label-set">
							{{quick_list_import_form.timer_group.label_tag}}
							{{quick_list_import_form.timer_group}}
						</div>
						<input type="submit" value="Import &amp; Delete QL"/>
					</form>
				</section>
			</article>
			<article class="forms-and-options forms-help sp-100 ll-25-right">			
				<section>
					<h1>Passwords</h1>
						<p>You can change your password here when you need to.</p>
				</section>
			</article>
			<article class="forms-and-options forms-normal sp-100 ll-75-left">
				<section>
					<h2>Change Password</h2>
					<form action={% url 'padsweb:settings_set_password' %} method="POST">
						{% csrf_token %}
							{{password_change_form.user_id}}
						<div class="forms-input-label-set">
							{{password_change_form.old_password.label_tag}}
							{{password_change_form.old_password}}
						</div>
						<div class="forms-input-label-set">
							{{password_change_form.new_password.label_tag}}
							{{password_change_form.new_password}}
						</div>
						<div class="forms-input-label-set">
							{{password_change_form.new_password_confirm.label_tag}}
							{{password_change_form.new_password_confirm}}
						</div>
						<input type="submit" value="Change Password"/>
					</form>
				</section>
				{% endif %}
		</article>
		{% else %}
		<div class="item-detail">
		<h1>What are you doing here?</h1>
			<p>Please sign in first to check your user info. You should only mess with your own account!</p>
		</div>
		{% endif %}
{% endblock %}